# Generated by Django 3.2.13 on 2023-02-12 05:02

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_editorjs_fields.fields.EditorJsTextField(null=True),
        ),
    ]
