# Generated by Django 3.2.13 on 2023-02-12 05:03

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(null=True),
        ),
    ]
