# Generated by Django 3.2.13 on 2023-02-12 06:23

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_editorjs_text',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
