# Generated by Django 3.2.13 on 2023-02-18 13:20

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_body_editorjs_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_editorjs_custom',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
    ]
