# Generated by Django 3.2.13 on 2023-02-19 11:15

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=django_editorjs_fields.fields.EditorJsTextField(),
        ),
    ]
