# Generated by Django 3.2.13 on 2023-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(default='한줄소개', max_length=1000),
        ),
    ]
