# Generated by Django 3.2.13 on 2023-03-16 10:39

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_froala',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
