# Generated by Django 3.2.13 on 2023-03-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_body_froala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_froala',
        ),
    ]
